FROM fabiocicerchia/nginx-lua:1.27.3-debian12.9

RUN apt-get update && \
    apt-get install -y python3 python3-venv libaugeas0 gcc less nano cron && \
    apt-get remove certbot && \
    luarocks install lua-cjson && \
    python3 -m venv /opt/certbot/ && \
    /opt/certbot/bin/pip install --upgrade pip && \
    /opt/certbot/bin/pip install certbot certbot-nginx && \
    ln -s /opt/certbot/bin/certbot /usr/bin/certbot
RUN rm -f /var/log/nginx/access.log /var/log/nginx/error.log && \
    touch /var/log/nginx/access.log /var/log/nginx/error.log
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY . /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && \
    chown -R root /usr/share/nginx/html && \
    chmod -R 777 /usr/share/nginx/html && \
    (crontab -l -u root 2>/dev/null; echo '0 2 1 */3 * certbot renew --quiet && systemctl restart nginx') | crontab -u root -
    
